version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '2007:2007'

    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
